# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-latest'

trigger:
- master

variables:
  buildConfiguration: 'release'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'

steps:
- task: NugetToolInstaller@1
- task: NuGetCommand@2
  inputs: 
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: dotnet build $(buildConfiguration)
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

- task: Npm@1
  displayName: "npm install"
  inputs:
    command: 'install'
    workingDir: 'ClientApp'

- task: Npm@1
  displayName: "npm run build:$(buildConfiguration)"
  inputs:
    command: 'custom'
    workingDir: 'ClientApp'
    customCommand: 'run build:$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: "dotnet publish $(buildConfiguration)"
  inputs:
    command: 'publish'
    publishWebProjects: True
    arguments: '-c $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True




