# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
    checkLatest: true
# MSBuild
# Build with MSBuild
- task: MSBuild@1
  inputs:
    solution: '**/*.sln' 
    msbuildLocationMethod: 'version' # Optional. Options: version, location
    msbuildVersion: 'latest' # Optional. Options: latest, 16.0, 15.0, 14.0, 12.0, 4.0
    msbuildArchitecture: 'x86' # Optional. Options: x86, x64
    msbuildLocation: # Optional
    platform: # Optional
    configuration: # Optional
    msbuildArguments: # Optional
    clean: false # Optional
    maximumCpuCount: false # Optional
    restoreNugetPackages: false # Optional
    logProjectEvents: false # Optional
    createLogFile: false # Optional
    logFileVerbosity: 'normal' # Optional. Options: quiet, minimal, normal, detailed, diagnostic

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(Pipeline.Workspace)
    artifactName: MyPipelineOutputs